# Generated by Django 4.2.3 on 2023-08-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_brand_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_eu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_us', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('size_uk', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('len_inch', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('len_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'sizes',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='api.size'),
        ),
    ]
