# Generated by Django 4.2.3 on 2023-08-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_size_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='len_cm',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='len_inch',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_uk',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_us',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
